# Site Settings
baseurl: ""
url: http://bootstrapbase.com
encoding: UTF-8

# Build Settings
markdown: kramdown
permalink: pretty

# Site Details
license: ""
license-url: ""
author: "BootstrapBase"

# Jekyll Redirect From Plugin for Redirects from BootstrapBase Old Version
gems:
  - jekyll-redirect-from