# Site Settings
baseurl: ""
url: http://layoutschool.com
encoding: UTF-8

# Build Settings
markdown: kramdown
permalink: pretty

# Site Details
license: ""
license-url: ""
author: "LayoutSchool"

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-redirect-from